name: CI
on: [push]
jobs:

  test_goAbstractor:
    name: Run Tests for Go Abstractor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.22"
      
      - name: Add Cover Tool
        working-directory: ./goAbstractor
        run: go get golang.org/x/tools/cmd/cover
      
      - name: Install dependencies
        working-directory: ./goAbstractor
        run: go get ./...

      - name: Run Tests
        working-directory: ./goAbstractor
        timeout-minutes: 10
        run: go test -cover ./...

  test_techDebtMetrics_windows:
    name: Run Tests for TechDebt Metrics on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Run Program
        working-directory: ./techDebtMetrics
        run: dotnet test

  test_techDebtMetrics_linux:
    name: Run Tests for TechDebt Metrics on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Run Program
        working-directory: ./techDebtMetrics
        run: dotnet test --os linux
