name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: '^1.22'
  DOTNET_VERSION: '8'

jobs:
  goAbstractor:
    strategy:
      fail-fast: false
      matrix:
        trials:
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest
        - name: MacOS
          os: macos-latest
    name: Go Abstractor (${{ matrix.trials.name }})
    runs-on: ${{ matrix.trials.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Add Cover Tool
        working-directory: ./goAbstractor
        run: go get golang.org/x/tools/cmd/cover
      - name: Install dependencies
        working-directory: ./goAbstractor
        run: go get ./...
      - name: Run Tests
        working-directory: ./goAbstractor
        timeout-minutes: 60
        run: go test -v -cover ./...

  techDebtMetrics:
    strategy:
      fail-fast: false
      matrix:
        trials:
        - name: Linux
          os: ubuntu-latest
          flags: --os linux
        - name: Windows
          os: windows-latest
          flags: --os win
        - name: MacOS
          os: macos-latest
          flags: --os osx
    name: TechDebt Metrics (${{ matrix.trials.name }})
    runs-on: ${{ matrix.trials.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Run Program
        working-directory: ./techDebtMetrics
        timeout-minutes: 60
        run: dotnet test -v detailed ${{ matrix.trials.flags }}
